#define CISCO_INT_F0 0
#define CISCO_INT_G0 1
#define CISCO_INT_G00 2
#define CISCO_INT_G01 3
#define CISCO_INT_S00 4
#define CISCO_INT_S01 5
#define CISCO_INT_PORTCH 6
#define CISCO_INT_VLAN 7

#define CISCO_MODE_ACCESS 8
#define CISCO_MODE_TRUNK 9
#define CISCO_MODE_ACTIVE 10
#define CISCO_MODE_PASSIVE 11
#define CISCO_MODE_DESIRABLE 12
#define CISCO_MODE_AUTO 13
