/************************************\
* Cisco Config Generator, v0.56      *
* (c)2021 pocketlinux32, Under GPLv3 *
* Ciscolib Constants Header File     *
\************************************/
#define CISCO_INT_F0 0
#define CISCO_INT_G0 1
#define CISCO_INT_G00 2
#define CISCO_INT_G01 3
#define CISCO_INT_S00 4
#define CISCO_INT_S01 5
#define CISCO_INT_F1 6
#define CISCO_INT_G1 7
#define CISCO_INT_G10 8
#define CISCO_INT_G11 9
#define CISCO_INT_VLAN 10
#define CISCO_INT_PORTCH 11

#define CISCO_MODE_ACCESS 16
#define CISCO_MODE_TRUNK 17
#define CISCO_MODE_ACTIVE 18
#define CISCO_MODE_PASSIVE 19
#define CISCO_MODE_DESIRABLE 20
#define CISCO_MODE_AUTO 21
#define CISCO_MODE_ON 22
#define CISCO_MODE_IN_PORTCH 23

#define CISCO_MODTYPE_TYPE 32
#define CISCO_MODTYPE_MODE 33
#define CISCO_MODTYPE_PORTS 34
#define CISCO_MODTYPE_DESC 35
#define CISCO_MODTYPE_ALLOW_VLAN 36
#define CISCO_MODTYPE_IP_ADDR 37
#define CISCO_MODTYPE_SUBMASK 38
#define CISCO_MODTYPE_GATEWAY 39

#define CISCO_ERROR_INVALID_ACTION 48
#define CISCO_ERROR_INVALID_VALUE 49
#define CISCO_ERROR_BUFFER_OVERFLOW 50
#define CISCO_ERROR_OUT_OF_RANGE 51
#define CISCO_ERROR_PL32LIB_GC 52
#define CISCO_ERROR_MISMATCHED_IPVER 53

