#define CISCO_INT_F0 uint8_t(0)
#define CISCO_INT_G0 uint8_t(1)
#define CISCO_INT_G00 uint8_t(2)
#define CISCO_INT_G01 uint8_t(3)
#define CISCO_INT_S00 uint8_t(4)
#define CISCO_INT_S01 uint8_t(5)
#define CISCO_INT_PORTCH uint8_t(6)
#define CISCO_INT_VLAN uint8_t(7)

#define CISCO_MODE_ACCESS uint8_t(8)
#define CISCO_MODE_TRUNK uint8_t(9)
#define CISCO_MODE_ACTIVE uint8_t(10)
#define CISCO_MODE_PASSIVE uint8_t(11)
#define CISCO_MODE_DESIRABLE uint8_t(12)
#define CISCO_MODE_AUTO uint8_t(13)
#define CISCO_MODE_IN_PORTCH uint8_t(14)

#define CISCO_MODTYPE_TYPE uint8_t(15)
#define CISCO_MODTYPE_MODE uint8_t(16)
#define CISCO_MODTYPE_PORTS uint8_t(17)
#define CISCO_MODTYPE_DESC uint8_t(18)
#define CISCO_MODTYPE_ALLOW_VLAN uint8_t(19)
#define CISCO_MODTYPE_IP_ADDR uint8_t(20)
#define CISCO_MODTYPE_SUBMASK uint8_t(21)
#define CISCO_MODTYPE_GATEWAY uint8_t(22)

#define CISCO_ERROR_INVALID_ACTION uint8_t(23)
#define CISCO_ERROR_INVALID_VALUE uint8_t(24)
#define CISCO_ERROR_BUFFER_OVERFLOW uint8_t(25)
#define CISCO_ERROR_OUT_OF_RANGE uint8_t(26)
#define CISCO_ERROR_PL32LIB_GC uint8_t(27)
#define CISCO_ERROR_MISMATCHED_IPVER uint8_t(28)

